### ISSUE TITLE
No longer supported

### ISSUE THREAD

**Issue by alamodey** [ElegantTeam/ETCollectionViewWaterFallLayout#2]
SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0.

Please update so it still works in Xcode 12.4

**Comment by VolleyZ** [comment]
> SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0.
> 
> Please update so it still works in Xcode 12.4

@alamodey please update.

**Comment by alamodey** [comment]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/55496019/108826992-2449ac00-7619-11eb-8143-a3b577512e61.png">

**Comment by VolleyZ** [comment]
@alamodey already update project by xcode12.1.
